### ISSUE TITLE
Option to look through discard pile

### ISSUE THREAD

**Issue by xxhellokittyluvrxx** [rally-the-troops/shores-of-tripoli#1]
There is no way to look through the discard pile. This would be particularly useful prior to playing a card such as Bainbridge Supplies Intel.

Disregard this request if the game rules officially state that you are not allowed to look through the discard pile.

**Comment by ccxvii** [comment]
I have implemented the optional rule and tournament play options that prohibit looking through the discard pile.

If you want to remember if you've played a certain card, you can search for the card name in the game log (just use the browser's normal search function).
